# Generated by Django 3.2.9 on 2022-01-07 08:14

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('base', '0004_auto_20211118_1213'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='rooms',
            options={'ordering': ['-updated_at', '-created_At']},
        ),
        migrations.RenameField(
            model_name='message',
            old_name='created_At',
            new_name='created_at',
        ),
        migrations.AddField(
            model_name='rooms',
            name='participants',
            field=models.ManyToManyField(blank=True, related_name='participants', to=settings.AUTH_USER_MODEL),
        ),
    ]
